---
- stat: path={{ thinpooldev }}
  register: thinpooldev_stat
- template: src=templates/storage.thinpool.conf.j2 dest=/etc/systemd/system/docker.service.d/storage.conf
  when: thinpooldev_stat.stat.exists == True
